# Generated by Django 3.1.2 on 2020-10-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201013_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='No Name', max_length=3),
        ),
    ]
