# Generated by Django 3.1.2 on 2020-10-24 10:22

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20201024_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='holder',
            field=models.ForeignKey(default=catalog.models.holder_default, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder_bookinstance_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
