# Generated by Django 3.1.2 on 2020-10-28 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_auto_20201024_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='bookers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_bookinstance_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
