# Generated by Django 3.1.2 on 2020-10-31 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20201028_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history_bookinstance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('w', 'waiting'), ('r', 'rejected'), ('a', 'available')], default='w', max_length=1)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_friend_set', to=settings.AUTH_USER_MODEL)),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requester_friend_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
